version: '3'

services:
  db_postgres:
    image: geographica/postgis:tasty_termite
    ports:
    - '5432:5432'
    volumes:
    - app-db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWD=postgres
#  web:
#    build: .
#    command: python3 server/manage.py runserver 0.0.0.0:8000
#    ports:
#      - 8000:8000
#    depends_on:
#      - db_postgres
#
volumes:
  app-db-data:
    driver: local
