# Generated by Django 2.2.2 on 2019-06-09 04:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='figure',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='figure',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='green',
            name='figure',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='ntopoly',
            name='figure',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, unique=True),
        ),
    ]
