# Generated by Django 2.2.2 on 2019-06-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='elevation',
            table='public"."elevation',
        ),
        migrations.AlterModelTable(
            name='zipcode',
            table='public"."zipcode',
        ),
    ]
