# Generated by Django 2.2.2 on 2019-06-08 17:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190608_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='green',
            name='figure',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
